### ISSUE TITLE
After install all the package in a conda env, got the error message! 

### ISSUE THREAD

**Issue by wang1946may7** [liuzuxin/OSRL#10]
hi, I got an error after install all the packages and run your code. 
Traceback (most recent call last):
  File "/home/ubuntu/OSRL/examples/train/train_bc.py", line 15, in <module>
    from fsrl.utils import WandbLogger
  File "/home/ubuntu/anaconda3/envs/OSRL/lib/python3.9/site-packages/fsrl/utils/__init__.py", line 3, in <module>
    from fsrl.utils.logger import BaseLogger, DummyLogger, TensorboardLogger, WandbLogger
  File "/home/ubuntu/anaconda3/envs/OSRL/lib/python3.9/site-packages/fsrl/utils/logger/__init__.py", line 4, in <module>
    from fsrl.utils.logger.tb_logger import TensorboardLogger
  File "/home/ubuntu/anaconda3/envs/OSRL/lib/python3.9/site-packages/fsrl/utils/logger/tb_logger.py", line 5, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/ubuntu/anaconda3/envs/OSRL/lib/python3.9/site-packages/torch/utils/__init__.py", line 4, in <module>
    from .throughput_benchmark import ThroughputBenchmark
  File "/home/ubuntu/anaconda3/envs/OSRL/lib/python3.9/site-packages/torch/utils/throughput_benchmark.py", line 2, in <module>
    import torch._C
ModuleNotFoundError: No module named 'torch._C'

**Comment by liuzuxin** [comment]
It seems that the PyTorch version doesn't support the `tensorboard` SummaryWriter. Could you show me your PyTorch version? 

You can also try to update your PyTorch version to `1.13.1` since this version works for us well.

**Comment by liuzuxin** [comment]
Your understanding is correct. The bolded $\mathbf{R}$ and $\mathbf{C}$ represent all the reward returns and cost returns in the trajectory, while $R(\tau_i^*)$ denotes the scalar return of the entire trajectory.
