### ISSUE TITLE
Unable to install the OApackage

### ISSUE THREAD

**Issue by shahaamirbader** [liuzuxin/OSRL#11]
Hi, 

I am trying to run the train_cdt.py as per instruction listed on github readme page. However, when I try to install the OApackage I get the following error. 

```
❯ pip install OApackage==2.7.6
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting OApackage==2.7.6
  Downloading OApackage-2.7.6.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 11.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /tmp/pip-install-1t4f2txe/oapackage_afdf46ec7c0d4ba1a2622e95ae5261fd/setup.py:128: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(swig_version) >= LooseVersion(swig_minimum_version):
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1t4f2txe/oapackage_afdf46ec7c0d4ba1a2622e95ae5261fd/setup.py", line 297, in <module>
          raise Exception('could not find a recent version if SWIG')
      Exception: could not find a recent version if SWIG
      swig_version 3.0.12, swig_executable /usr/bin/swig3.0
      Readthedocs environment: False
      checkZlib: compile and link
      find_packages: ['oapackage', 'tests']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I tried installing the dependencies within the conda environment as well as outside the environment, but the error persists. Any help in resolving the error will be appreciated.

**Comment by Ja4822** [comment]
@shahaamirbader Hi, it seems that the `swig` (version 3.0.12) package is out of date. Could you try `pip install swig==4.1.1` as listed [here](https://github.com/liuzuxin/OSRL/blob/main/setup.py#L32)? If this cannot solve your issue, could you share more details about your conda environment and how you installed the OSRL package, e.g. the command lines?

**Comment by shahaamirbader** [comment]
So seems like it's already installed. Here is what happens when I try to install it 

![image](https://github.com/liuzuxin/OSRL/assets/78397774/9ce72002-e0d1-407b-adc6-236fde53dbc4)

Here are the commands I ran to install the OSRL package

1. I started by creating a condo env on py 3.8
2. Then I cloned the GitHub repo and ran the install command while in the OSRL directory. The command was ```pip install -e ."
3. This installed all the requirements. 
4. Then I tried installing the OApackage using ```pip install OApackage==2.7.6``` and got the original error
5. Strangely if I try to run the cdt.py file I get the following response on terminal 
![image](https://github.com/liuzuxin/OSRL/assets/78397774/0624d640-7b2d-48a2-a2cd-35a929dc7e17)

**Comment by liuzuxin** [comment]
Did you activate your conda environment before executing `pip install`? It seems that the `swig` package was installed in your Ubuntu system library instead of conda's. You can check which `pip` are you using by running `which pip`. You might need to use `pip3` in some cases. After you activate your conda environment and make sure your pip is conda's, then try `pip install -e .`, check the `swig` package version, and then  `pip install OApackage==2.7.6`.

The prompt regarding wandb is because we by default use [`weight & bias`](https://wandb.ai/site)  as our logging tool. If you want to use `tensorboard`, you can comment and uncomment the following two lines in the training script: https://github.com/liuzuxin/OSRL/blob/8502b7d436562053494c2a90fd5ef544e77f6e39/examples/train/train_cdt.py#L42-L43

**Comment by shahaamirbader** [comment]
Thanks for the advice. Yes I activated the conda environment before executing the installation commands. Just to make things simple, and avoid issued with pip, I deleted the conda environment and ran all the installation in non-conda environment. Here is a pip list of all the packages that gets installed after running the command ```pip install -e .``` You can see the swig is installed here. 

```
 xubuntu@ccd93ae1026b  /homelocal  3rd Year  DT_RL  OSRL  main 
Package                      Version                         Editable project location
---------------------------- ------------------------------- ---------------------------------------------------------------------------------------
absl-py                      1.3.0
aiohttp                      3.8.4
aiosignal                    1.3.1
apex                         0.1
appdirs                      1.4.4
apturl                       0.5.2
argcomplete                  3.1.1
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
astor                        0.8.1
asttokens                    2.2.1
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        22.1.0
audioread                    3.0.0
av                           10.0.0
av2                          0.2.1
backcall                     0.2.0
beautifulsoup4               4.11.1
bleach                       1.5.0
blinker                      1.4
blis                         0.7.9
blosc2                       2.0.0
bullet-safety-gym            1.4.0
cachetools                   5.2.0
catalogue                    2.0.8
catfish                      1.4.13
certifi                      2022.12.7
cffi                         1.15.1
chardet                      3.0.4
charset-normalizer           2.1.1
click                        8.0.4
cloudpickle                  2.2.0
cmake                        3.24.1.1
colorama                     0.4.3
colorlog                     6.7.0
comm                         0.1.2
commonmark                   0.9.1
confection                   0.0.3
configobj                    5.0.6
contourpy                    1.0.6
cryptography                 2.8
cuda-python                  11.7.0+0.g95a2041.dirty
cudf                         22.10.0a0+316.gad1ba132d2.dirty
cugraph                      22.10.0a0+113.g6bbdadf8.dirty
cuml                         22.10.0a0+56.g3a8dea659.dirty
cupshelpers                  1.0
cupy-cuda118                 11.0.0
cycler                       0.11.0
cymem                        2.0.7
Cython                       0.29.32
dask                         2022.9.2
dask-cuda                    22.10.0a0+23.g62a1ee8
dask-cudf                    22.10.0a0+316.gad1ba132d2.dirty
dbus-python                  1.2.16
debugpy                      1.6.4
decorator                    5.1.1
defer                        1.0.6
defusedxml                   0.7.1
distlib                      0.3.6
distributed                  2022.9.2
distro                       1.4.0
distro-info                  0.23ubuntu1
dm-tree                      0.1.8
docker-pycreds               0.4.0
dsrl                         0.1.0
easy-runner                  0.1.0
entrypoints                  0.4
exceptiongroup               1.0.4
execnet                      1.9.0
executing                    1.2.0
expecttest                   0.1.3
Farama-Notifications         0.0.4
fast-safe-rl                 0.1.0
fastjsonschema               2.16.2
fastrlock                    0.8.1
filelock                     3.12.2
Flask                        2.2.2
flatbuffers                  23.3.3
fonttools                    4.38.0
frozenlist                   1.3.3
fsspec                       2022.11.0
gast                         0.4.0
gitdb                        4.0.10
GitPython                    3.1.31
glfw                         2.6.2
google-auth                  2.15.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
gpg                          1.13.1-unknown
graphsurgeon                 0.4.6
grpcio                       1.51.1
gym                          0.26.2
gym-notices                  0.0.8
gymnasium                    0.28.1
h5py                         2.10.0
hdf-compass                  0.7b8
HeapDict                     1.0.1
html5lib                     0.9999999
httplib2                     0.14.0
hypothesis                   5.35.1
idna                         3.4
imageio                      2.31.2
importlib-metadata           5.1.0
importlib-resources          5.10.1
iniconfig                    1.1.1
intel-openmp                 2021.4.0
ipykernel                    6.19.2
ipython                      8.7.0
ipython-genutils             0.2.0
itsdangerous                 2.1.2
jax                          0.4.8
jax-jumpy                    1.0.0
jedi                         0.18.2
Jinja2                       3.1.2
joblib                       1.2.0
json5                        0.9.10
jsonschema                   4.17.3
jupyter_client               7.4.8
jupyter_core                 5.1.0
jupyter-tensorboard          0.2.0
jupyterlab                   2.3.2
jupyterlab-pygments          0.2.2
jupyterlab-server            1.2.0
jupytext                     1.14.4
kaleido                      0.2.1
keras                        2.12.0
keyring                      18.0.1
kiwisolver                   1.4.4
langcodes                    3.3.0
language-selector            0.1
launchpadlib                 1.10.13
lazr.restfulclient           0.14.2
lazr.uri                     1.0.3
leveldb                      0.201
libclang                     16.0.0
librosa                      0.9.2
lightdm-gtk-greeter-settings 1.2.2
lightning-utilities          0.9.0
lit                          16.0.6
llvmlite                     0.39.1
locket                       1.0.0
lz4                          4.3.2
macaroonbakery               1.3.1
maddpg                       0.0.1                           /homelocal/3rd Year/Subsea/Vanilla_MADDPG/maddpg-master
Mako                         1.1.0
Markdown                     3.4.1
markdown-it-py               2.1.0
MarkupSafe                   2.1.1
matplotlib                   3.6.2
matplotlib-inline            0.1.6
mdit-py-plugins              0.3.3
mdurl                        0.1.2
menulibre                    2.2.1
mistune                      2.0.4
mkl                          2021.1.1
mkl-devel                    2021.1.1
mkl-include                  2021.1.1
ml-dtypes                    0.0.4
mock                         4.0.3
mpi4py                       3.0.3
mpmath                       1.2.1
msgpack                      1.0.4
mugshot                      0.4.2
mujoco                       2.3.0
multiagent                   0.0.1                           /homelocal/3rd Year/Subsea/Vanilla_MADDPG/maddpg-master/multiagent-particle-envs-master
multidict                    6.0.4
murmurhash                   1.0.9
mypy-extensions              1.0.0
nbclient                     0.7.2
nbconvert                    7.2.6
nbformat                     5.7.0
nest-asyncio                 1.5.6
networkx                     2.6.3
nose                         1.3.7
notebook                     6.4.10
nox                          2023.4.22
numba                        0.56.4
numexpr                      2.8.4
numpy                        1.23.5
numpy-stl                    3.0.1
nvidia-cublas-cu11           11.10.3.66
nvidia-cuda-cupti-cu11       11.7.101
nvidia-cuda-nvrtc-cu11       11.7.99
nvidia-cuda-runtime-cu11     11.7.99
nvidia-cudnn-cu11            8.5.0.96
nvidia-cufft-cu11            10.9.0.58
nvidia-curand-cu11           10.2.10.91
nvidia-cusolver-cu11         11.4.0.1
nvidia-cusparse-cu11         11.7.4.91
nvidia-dali-cuda110          1.20.0
nvidia-nccl-cu11             2.14.3
nvidia-nvtx-cu11             11.7.91
nvidia-pyindex               1.0.9
nvtx                         0.2.5
oauthlib                     3.2.2
olefile                      0.46
onboard                      1.4.1
onnx                         1.12.0
openai                       0.27.2
opencv                       4.6.0
opencv-python                4.8.0.74
opt-einsum                   3.3.0
osrl-lib                     0.1.0                           /homelocal/3rd Year/DT_RL/OSRL
packaging                    22.0
pandas                       1.5.2
pandocfilters                1.5.0
parso                        0.8.3
partd                        1.3.0
pathtools                    0.1.2
pathy                        0.10.1
pettingzoo                   1.24.0
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       9.2.0
pip                          23.2.1
pkgutil_resolve_name         1.3.10
platformdirs                 3.6.0
plotly                       5.11.0
pluggy                       1.0.0
polygraphy                   0.43.1
pooch                        1.6.0
preshed                      3.0.8
prettytable                  3.7.0
prometheus-client            0.15.0
prompt-toolkit               3.0.36
protobuf                     3.19.6
psutil                       5.9.5
ptyprocess                   0.7.0
pure-eval                    0.2.2
py-cpuinfo                   9.0.0
pyarrow                      9.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pybind11                     2.10.1
pybullet                     3.2.5
pycairo                      1.16.2
pycocotools                  2.0+nv0.7.1
pycparser                    2.21
pycups                       1.9.73
pydantic                     1.10.2
pygame                       2.1.0
pyglet                       1.5.27
Pygments                     2.13.0
PyGObject                    3.36.0
PyJWT                        1.7.1
pylibcugraph                 22.10.0a0+113.g6bbdadf8.dirty
pylibraft                    22.10.0a0+81.g08abc72.dirty
pymacaroons                  0.13.0
PyNaCl                       1.3.0
pynvml                       11.4.1
PyOpenGL                     3.1.7
pyparsing                    3.0.9
PyPDF2                       3.0.1
pyproj                       3.5.0
PyQt5                        5.14.1
pyrallis                     0.3.1
pyRFC3339                    1.1
pyrsistent                   0.19.2
pytest                       7.2.0
pytest-rerunfailures         10.3
pytest-shard                 0.1.2
pytest-xdist                 3.1.0
python-apt                   2.0.0+ubuntu0.20.4.8
python-dateutil              2.8.2
python-debian                0.1.36ubuntu1
python-gflags                3.1.2
python-hostlist              1.22
python-utils                 3.5.2
pytorch-lightning            2.0.5
pytorch-quantization         2.1.2
pytz                         2022.6
PyWavelets                   1.4.1
pyxattr                      0.6.1
pyxdg                        0.26
PyYAML                       6.0
pyzmq                        24.0.1
QtPy                         2.3.0
raft-dask                    22.10.0a0+81.g08abc72.dirty
ray                          2.1.0
regex                        2022.10.31
reportlab                    3.5.34
requests                     2.28.1
requests-oauthlib            1.3.1
requests-unixsocket          0.2.0
resampy                      0.4.2
rich                         12.6.0
rmm                          22.10.0a0+38.ge043158.dirty
rsa                          4.9
safety-gymnasium             0.4.0
scikit-image                 0.19.3
scikit-learn                 0.24.2
scipy                        1.10.1
SecretStorage                2.3.1
Send2Trash                   1.8.0
sentry-sdk                   1.25.1
setproctitle                 1.3.2
setuptools                   68.1.2
sgt-launcher                 0.2.5
simplejson                   3.16.0
sip                          4.19.21
six                          1.16.0
smart-open                   6.3.0
smmap                        5.0.0
sortedcontainers             2.4.0
soundfile                    0.11.0
soupsieve                    2.3.2.post1
spacy                        3.4.4
spacy-legacy                 3.0.10
spacy-loggers                1.0.4
sphinx-glpi-theme            0.3
srsly                        2.4.5
stack-data                   0.6.2
swig                         4.1.1
sympy                        1.11.1
systemd-python               234
tables                       3.8.0
tabulate                     0.9.0
tbb                          2021.7.1
tblib                        1.7.0
tenacity                     8.1.0
tensorboard                  2.14.0
tensorboard-data-server      0.7.0
tensorboard-plugin-wit       1.8.1
tensorboardX                 2.6.1
tensorflow                   1.8.0
tensorflow-estimator         2.12.0
tensorflow-io-gcs-filesystem 0.32.0
tensorrt                     8.5.1.7
termcolor                    2.2.0
terminado                    0.17.1
thinc                        8.1.5
threadpoolctl                3.1.0
tianshou                     0.5.1
tifffile                     2022.10.10
tinycss2                     1.2.1
toml                         0.10.2
tomli                        2.0.1
toolz                        0.12.0
torch                        1.13.1
torch-cluster                1.6.1+pt113cpu
torch-geometric              2.3.1
torch-scatter                2.1.1+pt113cpu
torch-sparse                 0.6.17+pt113cpu
torch-spline-conv            1.2.2+pt113cpu
torch-tensorrt               1.3.0a0
torchaudio                   2.0.2
torchmetrics                 1.0.1
torchtext                    0.13.0a0+fae8e8c
torchvision                  0.15.2
tornado                      6.1
tqdm                         4.64.1
traitlets                    5.7.1
transformer-engine           0.3.0
treelite                     2.4.0
treelite-runtime             2.4.0
triton                       2.0.0
typer                        0.7.0
typing_extensions            4.4.0
typing-inspect               0.9.0
ubuntu-advantage-tools       27.12
ubuntu-drivers-common        0.0.0
ucx-py                       0.27.0a0+29.ge9e81f8
uff                          0.6.9
unattended-upgrades          0.1
urllib3                      1.26.13
virtualenv                   20.23.1
ViTables                     3.0.2
vmas                         1.2.11
wadllib                      1.3.3
wandb                        0.14.2
wasabi                       0.10.1
wcwidth                      0.2.5
webencodings                 0.5.1
Werkzeug                     2.2.2
wheel                        0.38.4
wrapt                        1.14.1
wxPython                     4.0.7
xcffib                       0.8.1
xdoctest                     1.0.2
xgboost                      1.6.2
xkit                         0.0.0
xmltodict                    0.13.0
yarl                         1.8.2
youtube-dl                   2020.3.24
zict                         2.2.0
zipp                         3.11.0
```
And once I try to install the OAPackage == 2.7.6 I get the following error
```
 xubuntu@ccd93ae1026b  /homelocal  3rd Year  DT_RL  OSRL  main 
❯ pip install OApackage==2.7.6
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting OApackage==2.7.6
  Downloading OApackage-2.7.6.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 10.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /tmp/pip-install-3q8ysd5u/oapackage_0e3821feb4ed4bd293325e4941366713/setup.py:128: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(swig_version) >= LooseVersion(swig_minimum_version):
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3q8ysd5u/oapackage_0e3821feb4ed4bd293325e4941366713/setup.py", line 297, in <module>
          raise Exception('could not find a recent version if SWIG')
      Exception: could not find a recent version if SWIG
      swig_version 3.0.12, swig_executable /usr/bin/swig3.0
      Readthedocs environment: False
      checkZlib: compile and link
      find_packages: ['oapackage', 'tests']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I even try to install swig==3.0.12 as the error points towards swig version 3.0.12. But still the same problem.

Thanks in advance.

**Comment by shahaamirbader** [comment]
Okay so I figured out a way to install OApackage inside conda. Its as follows:
1. I removed the swig from non-condo environment using ```pip uninstall swig```
2. Then activated conda environment
3. Then installed swig using conda ```conda install -c anaconda swig```
4. Finally ran the OApackage command ```pip install OApackage==2.7.6```

Here is a screenshot 
![image](https://github.com/liuzuxin/OSRL/assets/78397774/700f89c5-e11f-4310-a698-0d9351989e32)

However, I am still unable to run the train_cdt.py, as I am getting this strange error which says ```No module named  'examples'```. See the screenshot below for error 
![image](https://github.com/liuzuxin/OSRL/assets/78397774/ba37a0dc-5a73-48e5-a158-1d3558e0f3cd)

**Comment by liuzuxin** [comment]
Glad to hear it was successfully installed. This error is strange, could you try to comment out these two lines? 

https://github.com/liuzuxin/OSRL/blob/8502b7d436562053494c2a90fd5ef544e77f6e39/examples/train/train_cdt.py#L52-L53

**Comment by shahaamirbader** [comment]
Seems to be working now, the training has started and is in progress. I will update here shortly. Meanwhile I have another question which I have posted separately. Thanks for the responses though.

**Comment by liuzuxin** [comment]
If you want to use wandb as the logger, you can refer to their tutorial regarding how to use it: https://docs.wandb.ai/quickstart
In generally, you don't need to do any visualization locally, you can login to your wandb account on their website to see the visualized training metrics.

If you don't want to use wandb, you can choose to use our tensorboard logger as I mentioned previously.

**Comment by shahaamirbader** [comment]
Thanks, closing this.
