### ISSUE TITLE
Questions about the paper details and CDT code bugs

### ISSUE THREAD

**Issue by ZhengYinan-AIR** [liuzuxin/OSRL#6]
Hi @liuzuxin, great work!  I encountered the following bugs and problems when using the OSRL library:

1. What are the specific values of the three distinct cost thresholds mentioned in Tables 3 and 6 of the [paper](http://arxiv.org/abs/2306.09303)？
2. When using the example code in OSRL, changing the environment will not modify the default **episode_len**, which remains constant at 300, is this a bug?
3. When I run the **CDT** code:
```
python ./examples/train/train_cdt.py --task OfflineCarPush1Gymnasium-v0 --cost_limit 5 --device "cuda:3"
```
but I got:
```
/root/anaconda3/envs/osrl/lib/python3.10/site-packages/numpy/lib/polynomial.py:667: RuntimeWarning: invalid value encountered in divide
  lhs /= scale
 ** On entry to DLASCL parameter number  4 had an illegal value
Traceback (most recent call last):
  File "/root/zyn/ydj_data_collection/OSRL/./examples/train/train_cdt.py", line 226, in <module>
    train()
  File "/root/anaconda3/envs/osrl/lib/python3.10/site-packages/pyrallis/argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/root/zyn/ydj_data_collection/OSRL/./examples/train/train_cdt.py", line 127, in train
    dataset = SequenceDataset(
  File "/root/zyn/ydj_data_collection/OSRL/osrl/common/dataset.py", line 726, in __init__
    self.idx, self.aug_data, self.pareto_frontier, self.indices = augmentation(
  File "/root/zyn/ydj_data_collection/OSRL/osrl/common/dataset.py", line 369, in augmentation
    pareto_frontier = np.poly1d(np.polyfit(cost_ret_pareto, rew_ret_pareto, deg=deg))
  File "<__array_function__ internals>", line 200, in polyfit
  File "/root/anaconda3/envs/osrl/lib/python3.10/site-packages/numpy/lib/polynomial.py", line 668, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "<__array_function__ internals>", line 200, in lstsq
  File "/root/anaconda3/envs/osrl/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2285, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "/root/anaconda3/envs/osrl/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 101, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares
wandb: Waiting for W&B process to finish... (failed 1).
```
How should I solve this problem?

**Comment by Ja4822** [comment]
Thank you for pointing this out. The arguments were not correctly passed. This bug is fixed. Could you run the command again? It should now run without any issues.

**Comment by Ja4822** [comment]
The cost thresholds are [10, 20, 40] for BulletSafetyGym and Metadrive environments and [20, 40, 80] for SafetyGymnasium environments. You can find more details in Appendix A.4.

**Comment by ZhengYinan-AIR** [comment]
THANKS!
